from django import forms 
import datetime
class CSVForm(forms.Form):

    file = forms.FileField(widget=forms.NumberInput(attrs={'class': 'file-upload-input', 'type':'file', 'onchange':'readURL(this);', 'accept':'csv'}), required=False)
    #<input class="file-upload-input" type='file' onchange="readURL(this);" accept=".csv" />

class sp_form(forms.Form):
    # Row 1
    d1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'd1_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    #d1_ = forms.CharField(widget=forms.TextInput(attrs={'class':'value',}), required=False)
    d1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    t1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 't1_range','class': 'slider-range', 'type':'range', 'value': '1.7', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    t1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    conf1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'conf1_range','class': 'slider-range', 'type':'range','value': '1000', 'step': '1', 'min': '1', 'max': '1000000'}), required=False)
    conf1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    rec1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'rec1_range','class': 'slider-range', 'type':'range', 'value': '200','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    rec1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dth1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dth1_range','class': 'slider-range', 'type':'range', 'value': '50','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    dth1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    un1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'un1_range','class': 'slider-range', 'type':'range','value': '220100.0', 'step': '.01', 'min': '1', 'max': '1000000.0'}), required=False)
    un1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    gas1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'gas1_range','class': 'slider-range', 'type':'range', 'value': '2.329','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    gas1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dies1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dies1_range','class': 'slider-range', 'type':'range', 'value': '3.013','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    dies1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    check1 = forms.BooleanField(required=False)

    # Row 2
    d2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'd2_range','class': 'slider-range', 'type':'range', 'value': '67.66', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    d2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    t2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 't2_range','class': 'slider-range', 'type':'range', 'value': '52', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    t2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    conf2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'conf2_range','class': 'slider-range', 'type':'range','value': '9000', 'step': '1', 'min': '1', 'max': '1000000'}), required=False)
    conf2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    rec2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'rec2_range','class': 'slider-range', 'type':'range', 'value': '500','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    rec2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dth2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dth2_range','class': 'slider-range', 'type':'range', 'value': '2','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    dth2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    un2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'un2_range','class': 'slider-range', 'type':'range','value': '920100.0', 'step': '.01', 'min': '1', 'max': '1000000.0'}), required=False)
    un2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    gas2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'gas2_range','class': 'slider-range', 'type':'range', 'value': '9.329','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    gas2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dies2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dies2_range','class': 'slider-range', 'type':'range', 'value': '1.013','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    dies2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    check2 = forms.BooleanField(required=False)

    
    # Row 3
    d3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'd3_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    d3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    t3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 't3_range','class': 'slider-range', 'type':'range', 'value': '1.7', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    t3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    conf3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'conf3_range','class': 'slider-range', 'type':'range','value': '1000', 'step': '1', 'min': '1', 'max': '1000000'}), required=False)
    conf3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    rec3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'rec3_range','class': 'slider-range', 'type':'range', 'value': '200','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    rec3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dth3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dth3_range','class': 'slider-range', 'type':'range', 'value': '50','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    dth3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    un3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'un3_range','class': 'slider-range', 'type':'range','value': '220100.0', 'step': '.01', 'min': '1', 'max': '1000000.0'}), required=False)
    un3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    gas3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'gas3_range','class': 'slider-range', 'type':'range', 'value': '2.329','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    gas3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dies3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dies3_range','class': 'slider-range', 'type':'range', 'value': '3.013','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    dies3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    check3 = forms.BooleanField(required=False)

class un_form(forms.Form):
    # Row 1
    g1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'g1_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '5000.00'}), required=False)
    g1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    d1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'd1_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    d1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    t1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 't1_range','class': 'slider-range', 'type':'range', 'value': '1.7', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    t1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    conf1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'conf1_range','class': 'slider-range', 'type':'range','value': '1000', 'step': '1', 'min': '1', 'max': '1000000'}), required=False)
    conf1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    rec1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'rec1_range','class': 'slider-range', 'type':'range', 'value': '200','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    rec1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dth1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dth1_range','class': 'slider-range', 'type':'range', 'value': '50','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    dth1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    gas1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'gas1_range','class': 'slider-range', 'type':'range', 'value': '2.329','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    gas1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dies1 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dies1_range','class': 'slider-range', 'type':'range', 'value': '3.013','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    dies1_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    check1 = forms.BooleanField(required=False)

    # Row 2
    g2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'g2_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '5000.00'}), required=False)
    g2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    d2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'd2_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    d2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    t2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 't2_range','class': 'slider-range', 'type':'range', 'value': '1.7', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    t2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    conf2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'conf2_range','class': 'slider-range', 'type':'range','value': '1000', 'step': '1', 'min': '1', 'max': '1000000'}), required=False)
    conf2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    rec2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'rec2_range','class': 'slider-range', 'type':'range', 'value': '200','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    rec2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dth2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dth2_range','class': 'slider-range', 'type':'range', 'value': '50','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    dth2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    gas2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'gas2_range','class': 'slider-range', 'type':'range', 'value': '2.329','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    gas2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dies2 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dies2_range','class': 'slider-range', 'type':'range', 'value': '3.013','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    dies2_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    check2 = forms.BooleanField(required=False)

    
    # Row 3
    g3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'g3_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '5000.00'}), required=False)
    g3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'})) 
    d3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'd3_range','class': 'slider-range', 'type':'range', 'value': '2.66', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    d3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    t3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 't3_range','class': 'slider-range', 'type':'range', 'value': '1.7', 'step': '.01', 'min': '1.00', 'max': '100.00'}), required=False)
    t3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    conf3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'conf3_range','class': 'slider-range', 'type':'range','value': '1000', 'step': '1', 'min': '1', 'max': '1000000'}), required=False)
    conf3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    rec3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'rec3_range','class': 'slider-range', 'type':'range', 'value': '200','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    rec3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dth3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dth3_range','class': 'slider-range', 'type':'range', 'value': '50','step': '1', 'min': '1', 'max': '1000000'}), required=False)
    dth3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    gas3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'gas3_range','class': 'slider-range', 'type':'range', 'value': '2.329','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    gas3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    dies3 = forms.CharField(widget=forms.NumberInput(attrs={'id': 'dies3_range','class': 'slider-range', 'type':'range', 'value': '3.013','step': '.001', 'min': '1', 'max': '25.000'}), required=False)
    dies3_= forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class':'input-value'}))
    check3 = forms.BooleanField(required=False)
